live_config_reload = true

[font]
size = 12

[font.bold]
family = "Monaco Nerd Font Mono"

[font.bold_italic]
family = "Monaco Nerd Font Mono"

[font.glyph_offset]
x = 0
y = 3

[font.italic]
family = "Monaco Nerd Font Mono"

[font.normal]
family = "Monaco Nerd Font Mono"

[font.offset]
x = 0
y = 9

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux new-session -A -D -s main"]
program = "/usr/bin/fish"

[window]
decorations = "None"
startup_mode = "Maximized"
# startup_mode = "FullScreen"
opacity = 0.7

[window.dimensions]
columns = 140
lines = 35

[window.padding]
x = 0
y = 0
# y = 22
